# vim: ts=2
---
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
    
  
  vars:
    vHome: /home/vagrant
      
  tasks:

  - include_role:
      name: gitlab

  - include_role:
      name: docker

  - name: Install python2.7
    apt:
      name: python2.7
      state: present

  - name: Install python-pip
    apt:
      name: python3-pip
      state: present

  - name: Install docker
    pip:
      name: docker

  - name: Add user to docker group
    user:
      name: vagrant
      group: docker

  - name: Run Tomcat container
    community.general.docker_container:
      name: TomCat7
      image: tomcat
      state: started
      volumes: 
        - /tomcat_data:/usr/local/tomcat/webapps
        - /tomcat_conf:/usr/local/tomcat/confbis
      ports:
        - "8888:8080"

  - name: Add GitLab Runner to keyring
    shell: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash

  - name: Install GitLab Runner
    apt:
      name: gitlab-runner
      state: present
